version: '3.6'
services:

  postgres_dev:
    environment: {"POSTGRES_DB":"tonka_dev","POSTGRES_PASSWORD":"tonka_dev","POSTGRES_USER":"tonka_dev"}
    image: 'postgres:14-alpine'
    restart: unless-stopped
    ports: ["55333:5432"]

  postgres_test:
    environment: {"POSTGRES_DB":"tonka_test","POSTGRES_PASSWORD":"tonka_test","POSTGRES_USER":"tonka_test"}
    image: 'postgres:14-alpine'
    restart: unless-stopped
    ports: ["55444:5432"]

